### ISSUE TITLE
click cancel in menu fails

### ISSUE THREAD

**Issue by ntoles** [PrincetonUniversity/Iseult#26] opened 2024-08-15 05:35 UTC
Fresh clone from github:
git clone git@github.com:bcaddy/Iseult.git
git checkout --track origin/master-tv2Spectra

[01:33][anatoly@stellar-vis1 ~/tig/bob/Iseult]$ git branch
  master
* master-tv2Spectra

When I open iseult from install directory, it opens the dialog. Now if I click Cancel on that dialog, it fails with this message:

[01:31][anatoly@stellar-vis1 ~/tig/bob/Iseult]$ ./iseult.py 
Traceback (most recent call last):
  File "/tigress/anatoly/bob/Iseult/./iseult.py", line 61, in <module>
    runMe(cmd_args)
  File "/tigress/anatoly/bob/Iseult/./src/main_app.py", line 3475, in runMe
    app = MainApp('Iseult', cmd_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tigress/anatoly/bob/Iseult/./src/main_app.py", line 1877, in __init__
    self.findDir()
  File "/tigress/anatoly/bob/Iseult/./src/main_app.py", line 2234, in findDir
    if not self.checkAndFindFilePaths():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tigress/anatoly/bob/Iseult/./src/main_app.py", line 2130, in checkAndFindFilePaths
    self.dirname = pathlib.Path(self.dirname)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/licensed/anaconda3/2023.9/lib/python3.11/pathlib.py", line 871, in __new__
    self = cls._from_parts(args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/licensed/anaconda3/2023.9/lib/python3.11/pathlib.py", line 509, in _from_parts
    drv, root, parts = self._parse_args(args)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/licensed/anaconda3/2023.9/lib/python3.11/pathlib.py", line 493, in _parse_args
    a = os.fspath(a)
        ^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not tuple

**Comment by ntoles** [comment] 2024-08-15 05:38
Also, I can't load any dataset. When I click OK on direcory that has PIC files, nothing happens and the file selector window does not close. 

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/4ba0235f-0052-48ad-9e29-74cba52d4cce">

**Comment by bcaddy** [comment] 2024-08-15 18:09
It exits with a similar message if you hit cancel before my changes too. It probably should exit since hitting cancel effectively leaves it without data.

I can reproduce the loop. It looks like it only happens for Tristan v2 datasets in the native nested directory format. I'll work on a fix.

**Comment by bcaddy** [comment] 2024-08-15 18:22
should be fixed now

**Closed** 2024-08-26 03:31 UTC
